# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /vol/home/s1560700/Documents/Master/jaar2/final_vec/piSat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /vol/home/s1560700/Documents/Master/jaar2/final_vec/piSat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /vol/home/s1560700/Documents/Master/jaar2/final_vec/piSat/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /vol/home/s1560700/Documents/Master/jaar2/final_vec/piSat/CMakeFiles /vol/home/s1560700/Documents/Master/jaar2/final_vec/piSat/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /vol/home/s1560700/Documents/Master/jaar2/final_vec/piSat/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named piSat

# Build rule for target.
piSat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 piSat
.PHONY : piSat

# fast build rule for target.
piSat/fast:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/build
.PHONY : piSat/fast

#=============================================================================
# Target rules for targets named distclean

# Build rule for target.
distclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distclean
.PHONY : distclean

# fast build rule for target.
distclean/fast:
	$(MAKE) -f CMakeFiles/distclean.dir/build.make CMakeFiles/distclean.dir/build
.PHONY : distclean/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f sylvan/CMakeFiles/ContinuousSubmit.dir/build.make sylvan/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f sylvan/CMakeFiles/ContinuousCoverage.dir/build.make sylvan/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f sylvan/CMakeFiles/ContinuousTest.dir/build.make sylvan/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f sylvan/CMakeFiles/ContinuousBuild.dir/build.make sylvan/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f sylvan/CMakeFiles/ContinuousMemCheck.dir/build.make sylvan/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f sylvan/CMakeFiles/Nightly.dir/build.make sylvan/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f sylvan/CMakeFiles/NightlyTest.dir/build.make sylvan/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f sylvan/CMakeFiles/NightlyUpdate.dir/build.make sylvan/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f sylvan/CMakeFiles/Continuous.dir/build.make sylvan/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f sylvan/CMakeFiles/NightlyBuild.dir/build.make sylvan/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f sylvan/CMakeFiles/NightlyStart.dir/build.make sylvan/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f sylvan/CMakeFiles/NightlyMemoryCheck.dir/build.make sylvan/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f sylvan/CMakeFiles/NightlyMemCheck.dir/build.make sylvan/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f sylvan/CMakeFiles/ExperimentalStart.dir/build.make sylvan/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f sylvan/CMakeFiles/ContinuousConfigure.dir/build.make sylvan/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f sylvan/CMakeFiles/NightlyCoverage.dir/build.make sylvan/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f sylvan/CMakeFiles/ExperimentalUpdate.dir/build.make sylvan/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f sylvan/CMakeFiles/ExperimentalConfigure.dir/build.make sylvan/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f sylvan/CMakeFiles/ExperimentalCoverage.dir/build.make sylvan/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f sylvan/CMakeFiles/ExperimentalBuild.dir/build.make sylvan/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f sylvan/CMakeFiles/NightlyConfigure.dir/build.make sylvan/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f sylvan/CMakeFiles/ExperimentalTest.dir/build.make sylvan/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f sylvan/CMakeFiles/ExperimentalMemCheck.dir/build.make sylvan/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f sylvan/CMakeFiles/Experimental.dir/build.make sylvan/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f sylvan/CMakeFiles/NightlySubmit.dir/build.make sylvan/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f sylvan/CMakeFiles/ExperimentalSubmit.dir/build.make sylvan/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f sylvan/CMakeFiles/ContinuousStart.dir/build.make sylvan/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f sylvan/CMakeFiles/ContinuousUpdate.dir/build.make sylvan/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named sylvan

# Build rule for target.
sylvan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sylvan
.PHONY : sylvan

# fast build rule for target.
sylvan/fast:
	$(MAKE) -f sylvan/src/CMakeFiles/sylvan.dir/build.make sylvan/src/CMakeFiles/sylvan.dir/build
.PHONY : sylvan/fast

#=============================================================================
# Target rules for targets named test_basic

# Build rule for target.
test_basic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_basic
.PHONY : test_basic

# fast build rule for target.
test_basic/fast:
	$(MAKE) -f sylvan/test/CMakeFiles/test_basic.dir/build.make sylvan/test/CMakeFiles/test_basic.dir/build
.PHONY : test_basic/fast

#=============================================================================
# Target rules for targets named test_cxx

# Build rule for target.
test_cxx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_cxx
.PHONY : test_cxx

# fast build rule for target.
test_cxx/fast:
	$(MAKE) -f sylvan/test/CMakeFiles/test_cxx.dir/build.make sylvan/test/CMakeFiles/test_cxx.dir/build
.PHONY : test_cxx/fast

src/DP/DP.o: src/DP/DP.cpp.o

.PHONY : src/DP/DP.o

# target to build an object file
src/DP/DP.cpp.o:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/DP/DP.cpp.o
.PHONY : src/DP/DP.cpp.o

src/DP/DP.i: src/DP/DP.cpp.i

.PHONY : src/DP/DP.i

# target to preprocess a source file
src/DP/DP.cpp.i:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/DP/DP.cpp.i
.PHONY : src/DP/DP.cpp.i

src/DP/DP.s: src/DP/DP.cpp.s

.PHONY : src/DP/DP.s

# target to generate assembly for a file
src/DP/DP.cpp.s:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/DP/DP.cpp.s
.PHONY : src/DP/DP.cpp.s

src/DPLL/DPLL.o: src/DPLL/DPLL.cpp.o

.PHONY : src/DPLL/DPLL.o

# target to build an object file
src/DPLL/DPLL.cpp.o:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/DPLL/DPLL.cpp.o
.PHONY : src/DPLL/DPLL.cpp.o

src/DPLL/DPLL.i: src/DPLL/DPLL.cpp.i

.PHONY : src/DPLL/DPLL.i

# target to preprocess a source file
src/DPLL/DPLL.cpp.i:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/DPLL/DPLL.cpp.i
.PHONY : src/DPLL/DPLL.cpp.i

src/DPLL/DPLL.s: src/DPLL/DPLL.cpp.s

.PHONY : src/DPLL/DPLL.s

# target to generate assembly for a file
src/DPLL/DPLL.cpp.s:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/DPLL/DPLL.cpp.s
.PHONY : src/DPLL/DPLL.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/structures/CNF.o: src/structures/CNF.cpp.o

.PHONY : src/structures/CNF.o

# target to build an object file
src/structures/CNF.cpp.o:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/structures/CNF.cpp.o
.PHONY : src/structures/CNF.cpp.o

src/structures/CNF.i: src/structures/CNF.cpp.i

.PHONY : src/structures/CNF.i

# target to preprocess a source file
src/structures/CNF.cpp.i:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/structures/CNF.cpp.i
.PHONY : src/structures/CNF.cpp.i

src/structures/CNF.s: src/structures/CNF.cpp.s

.PHONY : src/structures/CNF.s

# target to generate assembly for a file
src/structures/CNF.cpp.s:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/structures/CNF.cpp.s
.PHONY : src/structures/CNF.cpp.s

src/structures/Clause.o: src/structures/Clause.cpp.o

.PHONY : src/structures/Clause.o

# target to build an object file
src/structures/Clause.cpp.o:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/structures/Clause.cpp.o
.PHONY : src/structures/Clause.cpp.o

src/structures/Clause.i: src/structures/Clause.cpp.i

.PHONY : src/structures/Clause.i

# target to preprocess a source file
src/structures/Clause.cpp.i:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/structures/Clause.cpp.i
.PHONY : src/structures/Clause.cpp.i

src/structures/Clause.s: src/structures/Clause.cpp.s

.PHONY : src/structures/Clause.s

# target to generate assembly for a file
src/structures/Clause.cpp.s:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/structures/Clause.cpp.s
.PHONY : src/structures/Clause.cpp.s

src/structures/Variable.o: src/structures/Variable.cpp.o

.PHONY : src/structures/Variable.o

# target to build an object file
src/structures/Variable.cpp.o:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/structures/Variable.cpp.o
.PHONY : src/structures/Variable.cpp.o

src/structures/Variable.i: src/structures/Variable.cpp.i

.PHONY : src/structures/Variable.i

# target to preprocess a source file
src/structures/Variable.cpp.i:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/structures/Variable.cpp.i
.PHONY : src/structures/Variable.cpp.i

src/structures/Variable.s: src/structures/Variable.cpp.s

.PHONY : src/structures/Variable.s

# target to generate assembly for a file
src/structures/Variable.cpp.s:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/structures/Variable.cpp.s
.PHONY : src/structures/Variable.cpp.s

src/util/parsefile.o: src/util/parsefile.cpp.o

.PHONY : src/util/parsefile.o

# target to build an object file
src/util/parsefile.cpp.o:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/util/parsefile.cpp.o
.PHONY : src/util/parsefile.cpp.o

src/util/parsefile.i: src/util/parsefile.cpp.i

.PHONY : src/util/parsefile.i

# target to preprocess a source file
src/util/parsefile.cpp.i:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/util/parsefile.cpp.i
.PHONY : src/util/parsefile.cpp.i

src/util/parsefile.s: src/util/parsefile.cpp.s

.PHONY : src/util/parsefile.s

# target to generate assembly for a file
src/util/parsefile.cpp.s:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/util/parsefile.cpp.s
.PHONY : src/util/parsefile.cpp.s

src/util/util.o: src/util/util.cpp.o

.PHONY : src/util/util.o

# target to build an object file
src/util/util.cpp.o:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/util/util.cpp.o
.PHONY : src/util/util.cpp.o

src/util/util.i: src/util/util.cpp.i

.PHONY : src/util/util.i

# target to preprocess a source file
src/util/util.cpp.i:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/util/util.cpp.i
.PHONY : src/util/util.cpp.i

src/util/util.s: src/util/util.cpp.s

.PHONY : src/util/util.s

# target to generate assembly for a file
src/util/util.cpp.s:
	$(MAKE) -f CMakeFiles/piSat.dir/build.make CMakeFiles/piSat.dir/src/util/util.cpp.s
.PHONY : src/util/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... package"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... piSat"
	@echo "... distclean"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousTest"
	@echo "... ContinuousBuild"
	@echo "... ContinuousMemCheck"
	@echo "... Nightly"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... Continuous"
	@echo "... NightlyBuild"
	@echo "... NightlyStart"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ContinuousConfigure"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalUpdate"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalBuild"
	@echo "... NightlyConfigure"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalMemCheck"
	@echo "... Experimental"
	@echo "... NightlySubmit"
	@echo "... ExperimentalSubmit"
	@echo "... ContinuousStart"
	@echo "... ContinuousUpdate"
	@echo "... sylvan"
	@echo "... test_basic"
	@echo "... test_cxx"
	@echo "... src/DP/DP.o"
	@echo "... src/DP/DP.i"
	@echo "... src/DP/DP.s"
	@echo "... src/DPLL/DPLL.o"
	@echo "... src/DPLL/DPLL.i"
	@echo "... src/DPLL/DPLL.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/structures/CNF.o"
	@echo "... src/structures/CNF.i"
	@echo "... src/structures/CNF.s"
	@echo "... src/structures/Clause.o"
	@echo "... src/structures/Clause.i"
	@echo "... src/structures/Clause.s"
	@echo "... src/structures/Variable.o"
	@echo "... src/structures/Variable.i"
	@echo "... src/structures/Variable.s"
	@echo "... src/util/parsefile.o"
	@echo "... src/util/parsefile.i"
	@echo "... src/util/parsefile.s"
	@echo "... src/util/util.o"
	@echo "... src/util/util.i"
	@echo "... src/util/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

